repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        files: "py$"
      - id: trailing-whitespace
        files: "py$"
      - id: mixed-line-ending
-   repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: poetry run autoflake -r --remove-all-unused-imports --remove-unused-variables src/excel_postprocessor
        files: "py$"
        language: system
        types: [ python ]
      - id: isort
        name: isort
        entry: poetry run isort src/excel_postprocessor
        files: "py$"
        language: system
        types: [python]
      - id: black
        name: black
        entry: poetry run black src/excel_postprocessor
        files: "py$"
        language: system
        types: [python]
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py37-plus
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: poetry run mypy src/excel_postprocessor
        require_serial: true
        files: "py$"
        language: python
        types: [python]
        pass_filenames: false
        additional_dependencies: ["mypy==0.812"]
      - id: flake8
        name: flake8
        entry: poetry run flake8 src/excel_postprocessor
        exclude: "tests"
        files: "py$"
        language: system
        types: [python]
      - id: kacl-verify
        name: kacl-verify
        entry: poetry run kacl-cli verify
        language: system
        files: 'CHANGELOG.md'
        pass_filenames: false
